server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: sanjay
    url: jdbc:h2:mem:sanjaydb
    username: sanjay

plan-api:
 messages:
  planSaveSucc: Plan Saved Successfully
  planSaveFail: Plan Saving Failed
  planUpdateSucc: Plan Updated Successfully
  planUpdateFail: Plan Update Failed
  planDeleteSucc: Plan Deleted Successfully
  planDeleteFail: Plan Delete Fail
  planStatusChanged: Plan Status Changed Successfuly
  planStatusChangeFailed: Plan Status Change failed